name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: "recursive"
        fetch-depth: 0
        
    - name: Checkout libxposed/api
      uses: actions/checkout@v3
      with:
        repository: libxposed/api
        path: libxposed/api

    - name: Checkout libxposed/service
      uses: actions/checkout@v3
      with:
        repository: libxposed/service
        path: libxposed/service

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Build dependencies
      working-directory: libxposed
      run: |
        cd api
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        ./gradlew :api:publishApiPublicationToMavenLocal
        cd ..
        cd service
        echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
        ./gradlew :interface:publishInterfacePublicationToMavenLocal

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ImageDumper.apk
        path: app/build/outputs/apk/release/*.apk

